### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by OmgImAlexis** [gabrielcsapo/node-git-server#17]
I noticed there's a docs directory but no links to it.

**Comment by gabrielcsapo** [comment]
docs is located here http://www.gabrielcsapo.com/node-git-server/

**Comment by gabrielcsapo** [comment]
The page needs to be updated, going to update it later today with http://www.gabrielcsapo.com/tryitout/ so that it is a little more put together.

**Comment by gabrielcsapo** [comment]
I updated the docs in this commit https://github.com/gabrielcsapo/node-git-server/commit/3a1ebb29c895f7eb9e3e2e52f22875b0c4f2be09.

**Comment by OmgImAlexis** [comment]
@gabrielcsapo Glad to see the link added but the docs are still really sparse and missing key information such as what fields the first param actually returns.

For example with `repos.on('push', function (push) { ... }` what should push return?
All I can see from the docs is that it's a `http duplex object` with at least three fields `push.repo push.commit push.branch` but that's it. When looking at the docs link to `http-duplex` I noticed that's also a dead end as it now [points to a 404](https://github.com/gabrielcsapo/http-duplex).

Should I open a new issue for this?

**Comment by gabrielcsapo** [comment]
@OmgImAlexis would you be interested in helping me find the information missing and updating it accordingly?

**Comment by gabrielcsapo** [comment]
@OmgImAlexis fixed the link problem here https://github.com/gabrielcsapo/node-git-server/commit/df8d7fea451e6a1ab7897467d5e3694e02f0851a.

**Comment by gabrielcsapo** [comment]
@echopoint do you have any pointers for how the docs can be improved?

**Comment by echopoint** [comment]
I haven't actually read the docs yet. ;) I'll take a look and see what I can come up with. I've been referring to the code and dissecting it because I do like the project and am working on an interface for it.. I abhor gitlab, so this was very welcome. 

5. Nov 2017 21:50 by notifications@github.com:

**Comment by gabrielcsapo** [comment]
🙌🏻 You rock, if you are working on an interface I would love to help with
it!

**Comment by echopoint** [comment]
Ok. So now that HttpDuplex is in, I can add a little more doc to further explain it. Especially with the slight requirement of requiring newing the object instead of calling the function directly and it's destroy function, properties and methods that affect input / output. 

Service needs some fleshing out for sure. Describing it's purpose and scope of function so we can keep it as trim as possible. The problem with these kinds of projects is they are geared towards those who have worked with the bowels of the source control or want to learn how something like that can work or does work and by definition aren't as user friendly or consumable as some may like. I think as long as we stay on top of the documentation the issue will sort itself out fairly quickly.

The docs are a little better now, though I'm sure more will come to me once I delve a little further into an interface. Since then I'm sure it will have touched every part of the server functionality and probably require some extension to it.  

@OmgImAlexis pointed out the actual issue in the docs as it stands for the part.. with it just being a little spare on functional description.

**Comment by gabrielcsapo** [comment]
@echopoint okay I can start commenting more of the core code pieces using jsdoc and inline comments. 

As per the functional descriptions should it have a more in depth `how to use` section? I will send more time tommorow after work looking at what I can improve and submit a PR that both @echopoint and @OmgImAlexis can review if that works?

**Comment by echopoint** [comment]
Sure, I'm all for it. There could be a how to / tutorials section that could cover some basics and we can expand it from there as we go.
